version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: statsdb
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    # volumes:
    #   - db_data:/var/lib/mysql
    

  web:
    build: .
    depends_on:
      - db
    command: ["sh", "-c", "wait-for-it db:3306 -- sleep 20 && python migrate.py && python app.py"]
    ports:
      - "5000:5000"
    networks:
      - mynetwork 

networks:
  mynetwork:

volumes:
  db_data:
